install: true

jdk: oraclejdk8

language: java

cache:
  directories:
    - $HOME/.m2

os:
  - linux

before install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
script:
  - mvn clean test